// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMta5ACy8APXT-PP2Vht1BYaTHtiWVPc',
    appId: '1:355545609232:web:8c753831bb44399eaf0695',
    messagingSenderId: '355545609232',
    projectId: 'todolist-bed-af86d',
    authDomain: 'todolist-bed-af86d.firebaseapp.com',
    storageBucket: 'todolist-bed-af86d.firebasestorage.app',
    measurementId: 'G-Q0GYZ4DZMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75tkZV0xGx81LFcpB4PCX_qLyeNcXhpY',
    appId: '1:355545609232:android:be910254f85da111af0695',
    messagingSenderId: '355545609232',
    projectId: 'todolist-bed-af86d',
    storageBucket: 'todolist-bed-af86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSFFN5hpJjlKzuop_0tGYt5P_PBc6lzQ',
    appId: '1:355545609232:ios:5346407030640f22af0695',
    messagingSenderId: '355545609232',
    projectId: 'todolist-bed-af86d',
    storageBucket: 'todolist-bed-af86d.firebasestorage.app',
    iosBundleId: 'com.example.toDoListBed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSFFN5hpJjlKzuop_0tGYt5P_PBc6lzQ',
    appId: '1:355545609232:ios:5346407030640f22af0695',
    messagingSenderId: '355545609232',
    projectId: 'todolist-bed-af86d',
    storageBucket: 'todolist-bed-af86d.firebasestorage.app',
    iosBundleId: 'com.example.toDoListBed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsMta5ACy8APXT-PP2Vht1BYaTHtiWVPc',
    appId: '1:355545609232:web:a7faa19e1316eafaaf0695',
    messagingSenderId: '355545609232',
    projectId: 'todolist-bed-af86d',
    authDomain: 'todolist-bed-af86d.firebaseapp.com',
    storageBucket: 'todolist-bed-af86d.firebasestorage.app',
    measurementId: 'G-RF3V4ZJX8S',
  );

}